---
- hosts: all
  become: true
  pre_tasks:
    - assert:
        that:
          - "nfs_rhev_home is defined"
        msg: "nfs_rhev_home var is not defined"
  roles:
    - role: redhat_subscription_role
      tags: subscription

    # variables found in Vagrantfile extra_vars
    - role: ansible-role-hosts
      tags: etc_hosts

    - role: geerlingguy.nfs
      tags: nfs

    - role: rhev
      tags: rhev
