---
- hosts: all
  become: true
  pre_tasks:
    - assert:
        that:
          - "nfs_rhev_home is defined"
        msg: "nfs_rhev_home var is not defined"
  roles:
    - role: redhat_subscription_role
      tags: subscription
  	- role: ansible-role-hosts # variables found in Vagrantfile extra_vars
    - role: geerlingguy.nfs
      nfs_exports:
        - "{{ nfs_export_line }}"
      tags: nfs
    - role: rhev
      tags: rhev

