- name: install rhevm
  yum:
    name: rhevm

- name: attempt to connect via ovirt_auth
  ovirt_auth:
    url: https://{{ovirt_engine_host}}/ovirt-engine/api
    username: "{{ ovirt_username }}@{{ rhev_domain }}"
    password: "{{ ovirt_password }}"
  ignore_errors: yes

- name: revoke the SSO Token
  ovirt_auth:
    state: absent
    ovirt_auth: "{{ ovirt_auth }}"
  when: "ovirt_auth is defined"

- name: confirm that the nfs_rhev_home is set
  assert:
    that:
      - " nfs_rhev_home is defined "
    msg: "nfs_rhev_home is not defined"

- name: set nfs directory with the proper permissions
  file:
    path: "{{ nfs_rhev_home}}"
    owner: vdsm
    group: kvm
    mode: 0770
    state: directory

- name: update firewalld to allow NFS server to function
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ nfs_services }}"
  notify: reload firewalld
