- include: install.yml
  tags: rhev_install

- block:
  - assert:
      that:
        - "{{ item }} is defined"
      msg: "{{ item }} is not defined"
    with_items:
      - ovirt_password
      - ovirt_engine_host
    tags:
      - rhev_hypervisor
      - rhev_storage

  - name: get CA Cert from RHEV server
    get_url:
      url: "{{ rhev_ca_path }}"
      dest: "./ca.pem"
      validate_certs: no
    tags:
      - rhev_hypervisor
      - rhev_storage


  - name: Get SSO Token
    ovirt_auth:
      url: https://{{ovirt_engine_host}}/ovirt-engine/api
      ca_file: ca.pem
      username: "{{ ovirt_username }}@internal"
      password: "{{ ovirt_password }}"
    tags:
      - rhev_hypervisor
      - rhev_storage


  - include: hypervisors.yml
    tags: rhev_hypervisor

  - include: storage.yml
    tags: rhev_storage

  delegate_to: localhost
  always:
    - name: revoke the SSO Token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - rhev_hypervisor
        - rhev_storage


