- name: make sure ssh to root is permitted
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ".*PermitRootLogin"
    line: "PermitRootLogin yes"
  notify: restart ssh
  tags:
    - rhev_hypervisor
    - rhev_storage

- name: install ssh keys in root
  block:
    - file:
        path: /root/.ssh
        owner: root
        group: root
        mode: 0700
        state: directory
    - authorized_key:
        user: root
        key: "{{ lookup('file', './rhevm.pub.key') }}"
  tags:
    - rhev_hypervisor
    - rhev_storage

- block:
  - include_tasks: auth.yml
    tags:
      - rhev_hypervisor
      - rhev_storage


  - include: hypervisors.yml
    tags: rhev_hypervisor

  - include: storage.yml
    tags: rhev_storage

  always:
    - include_tasks: cleanup.yml
