- assert:
    that:
      - "{{ item }} is defined"
    msg: "{{ item }} is not defined"
  with_items:
    - storage_domain_name
    - ovirt_engine_host
    - nfs_rhev_home
    - rhel_hypervisor_name

- name: add data NFS storage domain
  ovirt_storage_domains:
    auth: "{{ ovirt_auth }}"
    name: "{{ storage_domain_name }}"
    host: "{{ rhel_hypervisor_name }}"
    data_center: Default
    nfs:
      address: "{{ ovirt_engine_host }}"
      path: "{{ nfs_rhev_home }}"

- name: Download Cirros Image from the internet
  get_url:
    url: "{{ cirros_img_url }}"
    dest: "{{ cirros_download_img_path }}"


- name: add cirros disk to RHEV
  ovirt_disk:
    name: "{{ vm_template_disk_name }}"
    size: 50MiB
    format: cow
    image_path: "{{ cirros_download_img_path }}"
    storage_domain:  rhel_nfs
    auth: "{{ ovirt_auth }}"
